"""add image_url and uploads table

Revision ID: 7c5080bd2ef7
Revises: bee814615f37
Create Date: 2026-07-03 10:19:01.843427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5080bd2ef7'
down_revision: Union[str, None] = 'bee814615f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('url_path', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index('idx_uploads_entity', 'uploads', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_uploads_orphan', 'uploads', ['entity_id'], unique=False)
    op.add_column('brands', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('industries', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('manufacturers', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('product_types', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_types', 'image_url')
    op.drop_column('manufacturers', 'image_url')
    op.drop_column('industries', 'image_url')
    op.drop_column('categories', 'image_url')
    op.drop_column('brands', 'image_url')
    op.drop_index('idx_uploads_orphan', table_name='uploads')
    op.drop_index('idx_uploads_entity', table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
