"""add manufacturer showcase fields

Revision ID: a1b2c3d4e5f6
Revises: d97c13524b3d
Create Date: 2026-07-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'd97c13524b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('manufacturers', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('manufacturers', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('manufacturers', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('manufacturers', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('manufacturers', sa.Column('featured_cable_ids', JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('manufacturers', sa.Column('featured_image', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('manufacturers', sa.Column('featured_image_sort', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('manufacturers', sa.Column('featured_text', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('manufacturers', sa.Column('featured_text_sort', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'featured_text_sort')
    op.drop_column('manufacturers', 'featured_text')
    op.drop_column('manufacturers', 'featured_image_sort')
    op.drop_column('manufacturers', 'featured_image')
    op.drop_column('manufacturers', 'featured_cable_ids')
    op.drop_column('manufacturers', 'email')
    op.drop_column('manufacturers', 'phone')
    op.drop_column('manufacturers', 'address')
    op.drop_column('manufacturers', 'founded_year')
    op.drop_column('manufacturers', 'description')
    # ### end Alembic commands ###
