"""add media_folders table and uploads.folder_id

Revision ID: d97c13524b3d
Revises: 7c5080bd2ef7
Create Date: 2026-07-04 02:20:39.586944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97c13524b3d'
down_revision: Union[str, None] = '7c5080bd2ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_folders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['media_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folder_parent_name')
    )
    op.add_column('uploads', sa.Column('folder_id', sa.BigInteger(), nullable=True))
    op.create_index('idx_uploads_folder', 'uploads', ['folder_id'], unique=False)
    op.create_foreign_key('fk_uploads_folder_id_media_folders', 'uploads', 'media_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_uploads_folder_id_media_folders', 'uploads', type_='foreignkey')
    op.drop_index('idx_uploads_folder', table_name='uploads')
    op.drop_column('uploads', 'folder_id')
    op.drop_table('media_folders')
    # ### end Alembic commands ###
